App\Domain\User\Model\User:
    type: entity
    table: users
    repositoryClass: App\Infrastructure\UserBundle\Repository\DoctrineUserRepository
    id:
        id:
            type: UserId
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            column: id
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            scale: 0
            length: 25
            unique: true
            nullable: false
            precision: 0
        password:
            type: string
            scale: 0
            length: 64
            unique: false
            nullable: false
            precision: 0
        email:
            type: string
            scale: 0
            length: 255
            unique: true
            nullable: false
            precision: 0
        isActive:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: is_active
        createdAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: created_at
        updatedAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: updated_at
        lastLogin:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: last_login
        locale:
            type: string
            scale: 0
            length: 100
            unique: false
            nullable: false
            precision: 0
        firstName:
            type: string
            scale: 0
            length: 100
            unique: false
            nullable: false
            precision: 0
            column: first_name
        lastName:
            type: string
            scale: 0
            length: 100
            unique: false
            nullable: false
            precision: 0
            column: last_name
    lifecycleCallbacks: {  }
